name: Compile SQLite3 for Android

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering from GitHub Actions tab

jobs:
  fetch-sqlite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Builder Source Code
        uses: actions/checkout@v4
        with:
          repository: AwaisKing/SQLite3AndroidBuild
          path: sqlite_source

      - name: Set up Java Development Kit (JDK)
        uses: actions/setup-java@v5.2.0
        with:
          distribution: 'graalvm'
          java-version: '21'

      - name: Install dependencies
        run: sudo apt update && sudo apt install -yq php php-cli gperf g++ git perl make unzip wget sed

      - name: Run Builder Script
        working-directory: sqlite_source
        run: |
          chmod 755 ./fetchNbuild.sh
          ./fetchNbuild.sh
          
